article1 = Article.create!(title:"完了", content:"完了")
issue1 = Issue.create!(title:"hello", content: "# Markdown \n ```a = b```", article_id: article1.id )
issue1_1 = issue1.children.create!(title:"hello2", content: "# Markdown \n ```a = b```", article_id: article1.id )
# issue1_1_1 = issue1_1.children.create!(title:"hello3", content: "# Markdown \n ```a = b```")
# issue1_1_1_1 = issue1_1_1.children.create!(title:"hello4", content: "# Markdown \n ```a = b```")
# issue1_1_1_1_1 = issue1_1_1_1.children.create!(title:"hello5", content: "# Markdown \n ```a = b```")

# issue2 = Issue.create!(title:"hello", content: "# Markdown \n ```a = b```")
# issue2_1 = issue2.children.create!(title:"hello2", content: "# Markdown \n ```a = b```")
# issue2_1_1 = issue2_1.children.create!(title:"hello3", content: "# Markdown \n ```a = b```")
# issue2_1_1_1 = issue2_1_1.children.create!(title:"hello4", content: "# Markdown \n ```a = b```")
# issue2_1_1_1_1 = issue2_1_1_1.children.create!(title:"hello5", content: "# Markdown \n ```a = b```")

# issue2_2 = issue2.children.create!(title:"hello2", content: "# Markdown \n ```a = b```")
# issue2_2_1 = issue2_2.children.create!(title:"hello3", content: "# Markdown \n ```a = b```")
# issue2_2_1_1 = issue2_2_1.children.create!(title:"hello4", content: "# Markdown \n ```a = b```")
# issue2_2_1_1_1 = issue2_2_1_1.children.create!(title:"hello5", content: "# Markdown \n ```a = b```")

# issue3 = Issue.create!(title:"good", content: "# Markdown \n ```a = b```")
# issue3_1 = issue3.children.create!(title:"good2", content: "# Markdown \n ```a = b```")
